/**
 * Maps ISO 3166-1 alpha-3 country codes to our rainfall region IDs.
 * Used by the WorldMapSelector to color countries by their hydrological region.
 */
export const COUNTRY_TO_REGION: Record<string, string> = {
  // ── Eastern US (handled via US state, but we map the whole country) ──
  USA: "us_east", // US shows as us_east; sub-regions handled by clicking

  // ── Canada ──
  CAN: "canada",

  // ── Central America & Caribbean ──
  MEX: "central_america",
  GTM: "central_america",
  BLZ: "central_america",
  HND: "central_america",
  SLV: "central_america",
  NIC: "central_america",
  CRI: "central_america",
  PAN: "central_america",
  CUB: "central_america",
  JAM: "central_america",
  HTI: "central_america",
  DOM: "central_america",
  TTO: "central_america",
  BRB: "central_america",
  PRI: "central_america",
  BHS: "central_america",

  // ── South America ──
  BRA: "south_america",
  ARG: "south_america",
  COL: "south_america",
  PER: "south_america",
  VEN: "south_america",
  CHL: "south_america",
  ECU: "south_america",
  BOL: "south_america",
  PRY: "south_america",
  URY: "south_america",
  GUY: "south_america",
  SUR: "south_america",
  GUF: "south_america",

  // ── Western Europe ──
  GBR: "western_europe",
  FRA: "western_europe",
  DEU: "western_europe",
  NLD: "western_europe",
  BEL: "western_europe",
  LUX: "western_europe",
  CHE: "western_europe",
  AUT: "western_europe",
  IRL: "western_europe",
  
  // ── Nordic & Baltic ──
  NOR: "nordic",
  SWE: "nordic",
  FIN: "nordic",
  DNK: "nordic",
  ISL: "nordic",
  EST: "nordic",
  LVA: "nordic",
  LTU: "nordic",

  // ── Eastern Europe ──
  POL: "eastern_europe",
  CZE: "eastern_europe",
  SVK: "eastern_europe",
  HUN: "eastern_europe",
  ROU: "eastern_europe",
  BGR: "eastern_europe",
  SRB: "eastern_europe",
  HRV: "eastern_europe",
  SVN: "eastern_europe",
  BIH: "eastern_europe",
  MNE: "eastern_europe",
  MKD: "eastern_europe",
  ALB: "eastern_europe",
  KOS: "eastern_europe",
  MDA: "eastern_europe",
  GEO: "eastern_europe",
  ARM: "eastern_europe",
  AZE: "eastern_europe",

  // ── Mediterranean ──
  ESP: "mediterranean",
  PRT: "mediterranean",
  ITA: "mediterranean",
  GRC: "mediterranean",
  TUR: "mediterranean",
  CYP: "mediterranean",
  MLT: "mediterranean",

  // ── Russia & Central Asia ──
  RUS: "russia_ca",
  UKR: "russia_ca",
  BLR: "russia_ca",
  KAZ: "russia_ca",
  UZB: "russia_ca",
  TKM: "russia_ca",
  KGZ: "russia_ca",
  TJK: "russia_ca",
  MNG: "russia_ca",

  // ── Middle East ──
  SAU: "middle_east",
  ARE: "middle_east",
  QAT: "middle_east",
  KWT: "middle_east",
  BHR: "middle_east",
  OMN: "middle_east",
  YEM: "middle_east",
  IRQ: "middle_east",
  JOR: "middle_east",
  LBN: "middle_east",
  SYR: "middle_east",
  ISR: "middle_east",
  PSE: "middle_east",
  IRN: "middle_east",
  AFG: "middle_east",

  // ── South Asia ──
  IND: "south_asia",
  PAK: "south_asia",
  BGD: "south_asia",
  LKA: "south_asia",
  NPL: "south_asia",
  BTN: "south_asia",
  MDV: "south_asia",
  MMR: "southeast_asia",

  // ── East Asia ──
  CHN: "east_asia",
  JPN: "east_asia",
  KOR: "east_asia",
  PRK: "east_asia",
  TWN: "east_asia",
  HKG: "east_asia",
  MAC: "east_asia",

  // ── Southeast Asia ──
  THA: "southeast_asia",
  VNM: "southeast_asia",
  MYS: "southeast_asia",
  SGP: "southeast_asia",
  IDN: "southeast_asia",
  PHL: "southeast_asia",
  KHM: "southeast_asia",
  LAO: "southeast_asia",
  BRN: "southeast_asia",
  TLS: "southeast_asia",

  // ── North & West Africa ──
  MAR: "north_africa",
  DZA: "north_africa",
  TUN: "north_africa",
  LBY: "north_africa",
  EGY: "north_africa",
  MRT: "north_africa",
  MLI: "north_africa",
  NER: "north_africa",
  TCD: "north_africa",
  NGA: "north_africa",
  GHA: "north_africa",
  CIV: "north_africa",
  SEN: "north_africa",
  GMB: "north_africa",
  GNB: "north_africa",
  GIN: "north_africa",
  SLE: "north_africa",
  LBR: "north_africa",
  BFA: "north_africa",
  TGO: "north_africa",
  BEN: "north_africa",
  CMR: "north_africa",
  GAB: "north_africa",
  COG: "north_africa",
  COD: "north_africa",
  CAF: "north_africa",
  GNQ: "north_africa",
  STP: "north_africa",
  ESH: "north_africa",

  // ── East & Southern Africa ──
  KEN: "east_africa",
  ETH: "east_africa",
  TZA: "east_africa",
  UGA: "east_africa",
  RWA: "east_africa",
  BDI: "east_africa",
  SOM: "east_africa",
  ERI: "east_africa",
  DJI: "east_africa",
  SDN: "east_africa",
  SSD: "east_africa",
  MOZ: "east_africa",
  MDG: "east_africa",
  MUS: "east_africa",
  ZAF: "east_africa",
  NAM: "east_africa",
  BWA: "east_africa",
  ZWE: "east_africa",
  ZMB: "east_africa",
  MWI: "east_africa",
  AGO: "east_africa",
  SWZ: "east_africa",
  LSO: "east_africa",
  COM: "east_africa",

  // ── Oceania & Pacific ──
  AUS: "oceania",
  NZL: "oceania",
  FJI: "oceania",
  PNG: "oceania",
  WSM: "oceania",
  SLB: "oceania",
  VUT: "oceania",
  NCL: "oceania",

  // ── Greenland (separate from Denmark for visual) ──
  GRL: "nordic",
};
