import { patternEquations, type PatternEquation } from "./patternEquations";

function escapeLatex(latex: string): string {
  return `$${latex}$`;
}

function equationToMarkdown(eq: PatternEquation): string {
  const lines: string[] = [];

  lines.push(`### ${eq.name}`);
  lines.push("");
  lines.push(`**Category:** ${eq.category}  `);
  lines.push(`**Pattern key:** \`${eq.pattern}\``);
  lines.push("");

  // Equations
  lines.push("#### Equations");
  lines.push("");
  for (const e of eq.equations) {
    lines.push(`**${e.label}**`);
    lines.push("");
    lines.push(`$$${e.latex}$$`);
    lines.push("");
    lines.push(`> ${e.description}`);
    lines.push("");
  }

  // Variables
  if (eq.variables.length > 0) {
    lines.push("#### Variables");
    lines.push("");
    lines.push("| Symbol | Meaning |");
    lines.push("|--------|---------|");
    for (const v of eq.variables) {
      lines.push(`| ${escapeLatex(v.symbol)} | ${v.meaning} |`);
    }
    lines.push("");
  }

  // Notes
  if (eq.notes) {
    lines.push("#### Notes");
    lines.push("");
    lines.push(eq.notes);
    lines.push("");
  }

  // Reference
  lines.push("#### Reference");
  lines.push("");
  lines.push(`- **${eq.reference.title}**`);
  lines.push(`  ${eq.reference.citation} (${eq.reference.year})`);
  if (eq.reference.link) {
    lines.push(`  [Link](${eq.reference.link})`);
  }
  lines.push("");

  lines.push("---");
  lines.push("");

  return lines.join("\n");
}

export function generateAllEquationsMarkdown(): string {
  const lines: string[] = [];

  lines.push("# Design Storm Equations Reference");
  lines.push("");
  lines.push(`> Auto-generated by [Rain Canvas Studio](https://rain-canvas-studio.lovable.app)  `);
  lines.push(`> ${patternEquations.length} documented design storm patterns  `);
  lines.push(`> Generated: ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // Table of contents
  lines.push("## Table of Contents");
  lines.push("");

  const categories = [
    { key: "cumulative" as const, label: "Cumulative (Mass Curve) Patterns" },
    { key: "intensity" as const, label: "Intensity-Based Patterns" },
    { key: "empirical" as const, label: "Empirical / Regional Patterns" },
  ];

  for (const cat of categories) {
    const items = patternEquations.filter((e) => e.category === cat.key);
    lines.push(`### ${cat.label} (${items.length})`);
    lines.push("");
    for (const eq of items) {
      const anchor = eq.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
      lines.push(`- [${eq.name}](#${anchor})`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Full entries by category
  for (const cat of categories) {
    const items = patternEquations.filter((e) => e.category === cat.key);
    lines.push(`## ${cat.label}`);
    lines.push("");

    for (const eq of items) {
      lines.push(equationToMarkdown(eq));
    }
  }

  // Bibliography
  lines.push("## Bibliography");
  lines.push("");
  const refs = [...new Map(
    patternEquations.map((eq) => [
      `${eq.reference.citation}-${eq.reference.year}`,
      eq.reference,
    ])
  ).values()].sort((a, b) => a.citation.localeCompare(b.citation));

  for (const ref of refs) {
    lines.push(`- ${ref.citation} (${ref.year}). *${ref.title}*.${ref.link ? ` [Link](${ref.link})` : ""}`);
  }
  lines.push("");

  return lines.join("\n");
}

export function downloadEquationsMarkdown(): void {
  const content = generateAllEquationsMarkdown();
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "design-storm-equations-reference.md";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
