import { type UnitSystem, convertDepth, convertIntensity, getDepthUnit, getIntensityUnit } from "@/lib/unitConversions";

export interface HecHmsGageOptions {
  gageName: string;
  startDate: string; // "01Jan2025"
  startTime: string; // "00:00"
  patternName: string;
  totalDepth: number;
  durationHours: number;
  timestepMinutes: number;
  unitSystem: UnitSystem;
  data: { time: number; intensity: number }[];
  projectName?: string;
  engineerName?: string;
  companyName?: string;
}

const MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const MONTH_MAP: Record<string, number> = Object.fromEntries(MONTH_NAMES.map((m, i) => [m, i]));

function parseHecDate(dateStr: string): Date {
  const day = parseInt(dateStr.substring(0, 2));
  const mon = dateStr.substring(2, 5);
  const year = parseInt(dateStr.substring(5));
  return new Date(year, MONTH_MAP[mon], day);
}

function formatHecDate(date: Date): string {
  return `${String(date.getDate()).padStart(2, '0')}${MONTH_NAMES[date.getMonth()]}${date.getFullYear()}`;
}

function calculateEndDateTime(startDate: string, startTime: string, durationHours: number) {
  const date = parseHecDate(startDate);
  const [h, m] = startTime.split(':').map(Number);
  date.setHours(h, m, 0, 0);
  date.setMinutes(date.getMinutes() + durationHours * 60);
  const endTime = `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
  return { endDate: formatHecDate(date), endTime };
}

function computeIncrementalDepths(options: HecHmsGageOptions): number[] {
  const stepHr = options.timestepMinutes / 60;
  return options.data.map(d => {
    const intensity = convertIntensity(d.intensity, 'USA', options.unitSystem);
    return intensity * stepHr;
  });
}

export function generateHecHmsGage(options: HecHmsGageOptions): string {
  const unitLabel = options.unitSystem === 'USA' ? 'IN' : 'MM';
  const { endDate, endTime } = calculateEndDateTime(options.startDate, options.startTime, options.durationHours);
  const depths = computeIncrementalDepths(options);
  const depthUnit = getDepthUnit(options.unitSystem);
  const totalConverted = convertDepth(options.totalDepth, 'USA', options.unitSystem);

  let out = `Gage: ${options.gageName}\n`;
  out += `  Description: Synthetic design storm generated by Rain Canvas Studio\n`;
  if (options.projectName) out += `  Project: ${options.projectName}\n`;
  if (options.engineerName) out += `  Engineer: ${options.engineerName}\n`;
  if (options.companyName) out += `  Company: ${options.companyName}\n`;
  out += `  Pattern: ${options.patternName}\n`;
  out += `  Total Depth: ${totalConverted.toFixed(3)} ${depthUnit}\n`;
  out += `  Duration: ${options.durationHours} hours\n`;
  out += `  URL: https://rain-canvas-studio.lovable.app\n`;
  out += `  \n`;
  out += `  Incremental: YES\n`;
  out += `  Units: ${unitLabel}\n`;
  out += `  Time Interval: ${options.timestepMinutes}\n`;
  out += `  Start Date: ${options.startDate}\n`;
  out += `  Start Time: ${options.startTime}\n`;
  out += `  End Date: ${endDate}\n`;
  out += `  End Time: ${endTime}\n`;
  out += `  Data:\n`;

  for (const d of depths) {
    out += `    ${d.toFixed(4)}\n`;
  }
  out += `End:\n`;
  return out;
}

export function generateHecDssImportCSV(options: HecHmsGageOptions): string {
  const unitLabel = options.unitSystem === 'USA' ? 'IN' : 'MM';
  const depths = computeIncrementalDepths(options);

  let out = `// HEC-DSS Import File\n`;
  out += `// Generated by Rain Canvas Studio\n`;
  if (options.projectName) out += `// Project: ${options.projectName}\n`;
  if (options.engineerName) out += `// Engineer: ${options.engineerName}\n`;
  if (options.companyName) out += `// Company: ${options.companyName}\n`;
  out += `// DSS Pathname: /SYNTHETIC/${options.gageName}/PRECIP-INC/${options.startDate}/${options.timestepMinutes}MIN/${options.patternName}/\n`;
  out += `//\n`;
  out += `Date,Time,Incremental Precipitation (${unitLabel})\n`;

  const currentDate = parseHecDate(options.startDate);
  const [startHr, startMin] = options.startTime.split(':').map(Number);
  currentDate.setHours(startHr, startMin, 0, 0);

  depths.forEach((d) => {
    const day = String(currentDate.getDate()).padStart(2, '0');
    const mon = MONTH_NAMES[currentDate.getMonth()];
    const year = currentDate.getFullYear();
    const hr = String(currentDate.getHours()).padStart(2, '0');
    const min = String(currentDate.getMinutes()).padStart(2, '0');
    out += `${day}${mon}${year},${hr}:${min},${d.toFixed(4)}\n`;
    currentDate.setMinutes(currentDate.getMinutes() + options.timestepMinutes);
  });

  return out;
}

export function generateHecHmsSetupGuide(options: HecHmsGageOptions): string {
  const unitLabel = options.unitSystem === 'USA' ? 'IN' : 'MM';
  const totalConverted = convertDepth(options.totalDepth, 'USA', options.unitSystem);
  const intervals = Math.ceil(options.durationHours * 60 / options.timestepMinutes);

  const projectLines: string[] = [];
  if (options.projectName) projectLines.push(`//    Project:   ${options.projectName}`);
  if (options.engineerName) projectLines.push(`//    Engineer:  ${options.engineerName}`);
  if (options.companyName) projectLines.push(`//    Company:   ${options.companyName}`);

  return `// ============================================================
// HEC-HMS Configuration Guide
// Generated by Rain Canvas Studio${projectLines.length > 0 ? '\n' + projectLines.join('\n') : ''}
// ============================================================
//
// To use this storm in HEC-HMS:
//
// 1. GAGE SETUP:
//    - Components → Time-Series Data Manager → Precipitation Gages
//    - Create new gage: "${options.gageName}"
//    - Data Type: Incremental
//    - Units: ${unitLabel}
//    - Time Interval: ${options.timestepMinutes} minutes
//    - Import the .gage file or paste DSS CSV data
//
// 2. METEOROLOGIC MODEL:
//    - Components → Meteorologic Model Manager → Create New
//    - Method: Specified Hyetograph
//    - Assign gage "${options.gageName}" to each subbasin
//
// 3. CONTROL SPECIFICATIONS:
//    - Start Date: ${options.startDate}
//    - End Date: Add buffer time for routing (typically +50%)
//    - Time Interval: ${options.timestepMinutes} minutes${options.projectName ? `\n//    - Description: ${options.projectName}` : ''}${options.engineerName ? `\n//    - Engineer: ${options.engineerName}` : ''}${options.companyName ? `\n//    - Company: ${options.companyName}` : ''}
//
// Storm Summary:
//    Pattern:   ${options.patternName}
//    Depth:     ${totalConverted.toFixed(3)} ${unitLabel}
//    Duration:  ${options.durationHours} hours
//    Timestep:  ${options.timestepMinutes} minutes
//    Intervals: ${intervals}
//
// Tested with HEC-HMS 4.9, 4.10, 4.11, and 4.12.
// Compatible with HEC-DSSVue 3.x for DSS imports.
// ============================================================`;
}

export type HecHmsFormat = 'gage' | 'dss-csv' | 'setup-guide';

export function exportHecHmsFile(format: HecHmsFormat, options: HecHmsGageOptions): { filename: string; content: string; mimeType: string } {
  switch (format) {
    case 'gage':
      return { filename: `${options.gageName}.gage`, content: generateHecHmsGage(options), mimeType: 'text/plain' };
    case 'dss-csv':
      return { filename: `${options.gageName}_dss_import.csv`, content: generateHecDssImportCSV(options), mimeType: 'text/csv' };
    case 'setup-guide':
      return { filename: `${options.gageName}_setup_guide.txt`, content: generateHecHmsSetupGuide(options), mimeType: 'text/plain' };
  }
}
