import type { PatternCardData } from "./PatternReferenceCard";

export const PATTERN_REFERENCE_DATA: PatternCardData[] = [
  {
    id: "scs-type-ii",
    name: "SCS Type II",
    region: "US Agency",
    shortDescription: "The most widely used design storm in the US. Center-peaked 24-hr distribution.",
    fullDescription: "The SCS Type II rainfall distribution was developed by the USDA Natural Resources Conservation Service for hydrologic analysis across the majority of the continental United States. It represents a 24-hour storm event with rainfall concentrated in the middle, producing a sharp peak critical for sizing stormwater infrastructure. The distribution is derived from analysis of NWS rainfall records and IDF curves.",
    history: "Published in SCS Technical Release 55 (TR-55) in 1986 as an update to earlier work in NEH-4. The four SCS types (I, IA, II, III) were developed by Victor Mockus at the SCS. Type II covers the largest geographic area and remains the default in most US states.",
    equation: "P(t)/P₂₄ = Tabulated cumulative ratios from TR-55 Table 6.1\n\nIncremental depth = P(tᵢ) - P(tᵢ₋₁)\nIntensity = Incremental depth / Δt",
    equationDescription: "Defined by a table of cumulative rainfall fractions at specified time intervals, not a closed-form equation. Tabulated values are interpolated for any desired timestep.",
    parameters: [
      { name: "Total Depth", symbol: "P₂₄", description: "24-hour rainfall depth from IDF/Atlas 14", defaultValue: "Location-dependent", range: "0.5–20+ inches" },
      { name: "Duration", symbol: "D", description: "Fixed at 24 hours for standard application", defaultValue: "24 hr", range: "24 hr (standard)" },
    ],
    peakPosition: "50% of duration (12:00)",
    peakIntensityRatio: "~5.5× average intensity",
    applicableRegions: ["Eastern US (east of 105°W)", "Central US (Great Plains)", "Pacific Northwest (east of Cascades)", "Most of Texas", "Midwest", "Northeast", "Southeast (except coastal FL)"],
    typicalDurations: ["24 hours"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "25-yr", "50-yr", "100-yr", "500-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "FEMA (Nationwide)", status: "accepted", notes: "Accepted for FIS flood frequency analysis" },
      { jurisdiction: "USACE (Nationwide)", status: "accepted", notes: "Accepted for Section 404/NEPA analysis" },
      { jurisdiction: "TxDOT (Texas)", status: "required", notes: "Required per TxDOT Hydraulic Design Manual" },
      { jurisdiction: "NCDOT (North Carolina)", status: "required", notes: "Required for all DOT drainage design" },
      { jurisdiction: "GDOT (Georgia)", status: "required" },
      { jurisdiction: "City of Houston", status: "required", notes: "Required per Infrastructure Design Manual" },
      { jurisdiction: "FDOT (Florida)", status: "not-accepted", notes: "Use FDOT Zone-specific distributions" },
      { jurisdiction: "Caltrans (California)", status: "not-accepted", notes: "Use SCS Type I or IA for most of California" },
    ],
    standardReference: "USDA-NRCS Technical Release 55 (TR-55), June 1986, Table 6.1",
    standardUrl: "https://www.nrcs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb1044171.pdf",
    characteristicShape: "Center-peaked",
    similarPatterns: ["SCS Type I", "SCS Type IA", "SCS Type III", "Huff 3rd Quartile"],
    differenceNotes: "Type II has the most intense peak of the four SCS types. Type III is similar but with a flatter, broader peak suited for tropical coastal areas. Huff 3rd Quartile has a similar center-peaked shape but is derived from Illinois gauge data.",
    lastVerified: "2025-01",
    dataSource: "TR-55 Table 6.1 + WinTR-55 validation",
  },
  {
    id: "scs-type-i",
    name: "SCS Type I",
    region: "US Agency",
    shortDescription: "Pacific maritime climate pattern with earlier peak at ~40% of duration.",
    fullDescription: "Designed for areas with wet winters and dry summers along the Pacific coast. The earlier peak reflects the more gradual rainfall patterns typical of maritime climates.",
    history: "Part of the original four SCS distributions published in TR-55 (1986). Covers the Pacific coast from southern California through coastal Oregon.",
    equation: "P(t)/P₂₄ = Tabulated cumulative ratios from TR-55 Table 6.1",
    equationDescription: "Tabulated cumulative distribution specific to Pacific maritime climate.",
    parameters: [
      { name: "Total Depth", symbol: "P₂₄", description: "24-hour rainfall depth", defaultValue: "Location-dependent", range: "0.5–15 inches" },
    ],
    peakPosition: "40% of duration (9:36)",
    peakIntensityRatio: "~4.0× average intensity",
    applicableRegions: ["Southern California", "Coastal Oregon", "Northern California inland"],
    typicalDurations: ["24 hours"],
    typicalReturnPeriods: ["2-yr", "10-yr", "25-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "Caltrans", status: "required", notes: "Required for most of California" },
      { jurisdiction: "FEMA", status: "accepted" },
    ],
    standardReference: "USDA-NRCS TR-55, Table 6.1",
    characteristicShape: "Early-peaked",
    similarPatterns: ["SCS Type IA", "SCS Type II"],
    differenceNotes: "Type I peaks earlier than Type II. Type IA is even more front-loaded for the wettest Pacific Northwest areas.",
    lastVerified: "2025-01",
    dataSource: "TR-55 Table 6.1",
  },
  {
    id: "euler-type-ii",
    name: "Euler Type II",
    region: "European",
    shortDescription: "German/European standard with peak at ~30% of duration, widely used for sewer design.",
    fullDescription: "The Euler Type II distribution places peak intensity at approximately 30% of the storm duration, derived from IDF curve disaggregation. It is the standard pattern for urban drainage design in Germany per DWA-A 118 and is widely adopted across Central Europe.",
    history: "Developed from the Euler method of IDF curve disaggregation, standardized by the Deutsche Vereinigung für Wasserwirtschaft (DWA). The method rearranges IDF-derived blocks so the peak occurs at a specified position (30% for Type II).",
    equation: "Δd(i) = a·(i·Δt)^(−b) · Δt\n\nBlocks sorted descending, then rearranged:\n- Largest block placed at r·D (r=0.3 for Type II)\n- Remaining blocks alternate before/after peak",
    equationDescription: "IDF curve is sampled at intervals Δt. Each interval's incremental depth is computed. Blocks are rearranged with peak at 30% of duration, maintaining mass balance.",
    parameters: [
      { name: "Total Depth", symbol: "P", description: "Design rainfall depth from KOSTRA-DWD", defaultValue: "Location-dependent", range: "10–200 mm" },
      { name: "Peak Position", symbol: "r", description: "Fraction of duration for peak", defaultValue: "0.3", range: "0.2–0.5" },
    ],
    peakPosition: "30% of duration",
    peakIntensityRatio: "~4–6× average intensity",
    applicableRegions: ["Germany", "Austria", "Switzerland", "Netherlands", "Central Europe"],
    typicalDurations: ["0.5 hr", "1 hr", "2 hr", "3 hr", "6 hr"],
    typicalReturnPeriods: ["1-yr", "2-yr", "5-yr", "10-yr", "30-yr", "50-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "DWA (Germany)", status: "required", notes: "DWA-A 118 standard for sewer design" },
      { jurisdiction: "ÖWAV (Austria)", status: "accepted" },
      { jurisdiction: "VSA (Switzerland)", status: "accepted" },
    ],
    standardReference: "DWA-A 118, DWA-M 553 (2012)",
    characteristicShape: "Front-peaked (30%)",
    similarPatterns: ["Euler Type I", "Alternating Block", "Chicago Storm"],
    differenceNotes: "Euler Type I places peak at the very start (r=0). Alternating Block centers the peak (r=0.5). Chicago Storm uses a continuous equation rather than block rearrangement.",
    lastVerified: "2025-01",
    dataSource: "DWA-A 118 / KOSTRA-DWD 2020",
  },
  {
    id: "chicago-storm",
    name: "Chicago Storm",
    region: "International",
    shortDescription: "IDF-derived pattern with adjustable peak via the r-parameter. Globally applicable.",
    fullDescription: "The Chicago Design Storm (Keifer & Chu, 1957) derives a continuous hyetograph directly from the IDF curve parameters. The peak position is controlled by the 'r' parameter (advancement coefficient), making it versatile for any location with IDF data.",
    history: "Developed by Keifer and Chu at the Illinois Institute of Technology in 1957 for Chicago's sewer system design. Despite the name, it is applicable worldwide wherever IDF curves are available.",
    equation: "Before peak: i(t) = a·[(1-r)·tᵇ + c] / [(1-r)·t + c]^(1+b)\nAfter peak:  i(t) = a·[r·tᵇ + c] / [r·t + c]^(1+b)",
    equationDescription: "Continuous intensity function derived from IDF equation i = a/(t+c)^b. The r parameter controls peak position (0 = front, 0.5 = center, 1 = back).",
    parameters: [
      { name: "IDF Parameter a", symbol: "a", description: "IDF curve coefficient", defaultValue: "Location-dependent", range: "Varies" },
      { name: "IDF Parameter b", symbol: "b", description: "IDF curve exponent", defaultValue: "~0.7–0.9", range: "0.5–1.0" },
      { name: "IDF Parameter c", symbol: "c", description: "IDF curve offset", defaultValue: "~5–15 min", range: "0–30 min" },
      { name: "Advancement Coefficient", symbol: "r", description: "Peak position ratio", defaultValue: "0.375", range: "0.0–1.0" },
    ],
    peakPosition: "37.5% of duration (default r=0.375)",
    peakIntensityRatio: "~6–8× average intensity",
    applicableRegions: ["Global (anywhere with IDF data)", "North America", "Europe", "Asia"],
    typicalDurations: ["0.5 hr", "1 hr", "2 hr", "3 hr", "6 hr"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "25-yr", "50-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "MWRD (Chicago)", status: "accepted", notes: "Accepted alongside Huff distributions" },
      { jurisdiction: "Various international", status: "accepted", notes: "Widely used in academic and consulting practice" },
    ],
    standardReference: "Keifer, C.J. & Chu, H.H. (1957). 'Synthetic Storm Pattern for Drainage Design.' ASCE Journal of the Hydraulics Division.",
    characteristicShape: "Adjustable-peaked",
    similarPatterns: ["Alternating Block", "Euler Type I", "Euler Type II"],
    differenceNotes: "Chicago Storm uses a continuous mathematical function while Alternating Block uses discrete IDF-derived blocks. Chicago produces smoother hyetographs.",
    lastVerified: "2025-01",
    dataSource: "Keifer & Chu (1957)",
  },
  {
    id: "huff-3rd-quartile",
    name: "Huff 3rd Quartile",
    region: "US Agency",
    shortDescription: "Center-peaked probabilistic distribution from Illinois gauge data. Peak at 50–75% of duration.",
    fullDescription: "Huff distributions are probabilistic patterns derived from analysis of over 400 storms measured at dense rain gauge networks in central Illinois. The 3rd Quartile variant peaks in the third quarter of the storm duration and is recommended for storms lasting 12–24 hours.",
    history: "Developed by Floyd A. Huff at the Illinois State Water Survey in 1967. Based on extensive analysis of recording rain gauge data from 49 stations. The four quartile types correspond to the quarter of the storm duration in which the heaviest rainfall occurs.",
    equation: "Dimensionless cumulative curve (50th percentile)\nTabulated at 5% time increments",
    equationDescription: "Probabilistic distribution defined by percentile curves (10th, 25th, 50th, 75th, 90th). The 50th percentile (median) curve is typically used for design.",
    parameters: [
      { name: "Total Depth", symbol: "P", description: "Design rainfall depth", defaultValue: "Location-dependent", range: "0.5–10 inches" },
      { name: "Percentile", symbol: "%ile", description: "Probability level", defaultValue: "50th (median)", range: "10th–90th" },
    ],
    peakPosition: "50–75% of duration",
    peakIntensityRatio: "~3–4× average intensity",
    applicableRegions: ["Illinois", "Midwest US", "Great Lakes region"],
    typicalDurations: ["12 hr", "24 hr"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "25-yr", "50-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "MWRD (Chicago)", status: "accepted", notes: "Accepted alongside Chicago Storm" },
      { jurisdiction: "IDOT (Illinois)", status: "accepted" },
      { jurisdiction: "FEMA", status: "accepted" },
    ],
    standardReference: "Huff, F.A. (1967). 'Time Distribution of Rainfall in Heavy Storms.' Water Resources Research, 3(4).",
    characteristicShape: "Center-to-late peaked",
    similarPatterns: ["Huff 1st Quartile", "Huff 2nd Quartile", "Huff 4th Quartile", "SCS Type II"],
    differenceNotes: "Huff distributions are empirically derived from gauge data, while SCS types are derived from IDF curves. Huff 3rd Quartile is less peaked than SCS Type II.",
    lastVerified: "2025-01",
    dataSource: "Illinois State Water Survey Bulletin 71",
  },
  {
    id: "alternating-block",
    name: "Alternating Block Method",
    region: "International",
    shortDescription: "IDF-derived center-peaked pattern. The universal fallback when no regional standard exists.",
    fullDescription: "The Alternating Block Method creates a design storm hyetograph directly from IDF curve data by computing incremental rainfall depths for successive time intervals and arranging them in a symmetric, center-peaked pattern. It is the most universally applicable synthetic storm method.",
    history: "Described in Chow, Maidment & Mays (1988) 'Applied Hydrology' and widely adopted as the standard method in hydrology textbooks. Used globally as a default when jurisdiction-specific distributions are not mandated.",
    equation: "1. From IDF: P(Δt) = i(Δt)·Δt for each duration\n2. ΔP(n) = P(n·Δt) - P((n-1)·Δt)\n3. Rank ΔP descending\n4. Place largest at center, alternate left/right",
    equationDescription: "Discrete block arrangement preserving IDF mass balance. Each block represents an incremental rainfall depth derived from the IDF curve.",
    parameters: [
      { name: "IDF Data", symbol: "i(d,T)", description: "Intensity-Duration-Frequency relationship", defaultValue: "Location-dependent", range: "Varies" },
    ],
    peakPosition: "50% of duration (center)",
    peakIntensityRatio: "~5–7× average intensity",
    applicableRegions: ["Global", "Any location with IDF data"],
    typicalDurations: ["1 hr", "2 hr", "3 hr", "6 hr", "12 hr", "24 hr"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "25-yr", "50-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "General practice", status: "accepted", notes: "Universally accepted where IDF data exists" },
      { jurisdiction: "Academic/textbook", status: "preferred", notes: "Standard method in Applied Hydrology (Chow et al.)" },
    ],
    standardReference: "Chow, V.T., Maidment, D.R. & Mays, L.W. (1988). Applied Hydrology. McGraw-Hill.",
    characteristicShape: "Center-peaked (symmetric)",
    similarPatterns: ["Chicago Storm", "Euler Type II", "Balanced Storm"],
    differenceNotes: "Alternating Block uses discrete blocks from IDF sampling; Chicago Storm uses a continuous function. Alternating Block always centers the peak; Chicago allows adjustment via the r parameter.",
    lastVerified: "2025-01",
    dataSource: "Chow et al. (1988)",
  },
  {
    id: "feh-uk",
    name: "FEH (UK)",
    region: "UK/ICM",
    shortDescription: "Flood Estimation Handbook standard for UK rainfall. 75% summer / 50% winter profiles.",
    fullDescription: "The FEH rainfall profile is the current UK standard for design rainfall estimation, replacing the older FSR/FEH method. It uses a symmetrical profile with the percentage of rainfall occurring in the peak period varying by season: 75% summer, 50% winter.",
    history: "Published by the Centre for Ecology and Hydrology (CEH) in the Flood Estimation Handbook (1999, updated 2013). Supersedes the FSR 1975 methodology for most UK applications.",
    equation: "Symmetric profile with seasonal peak ratios\nSummer: 75% of rainfall in central third\nWinter: 50% of rainfall in central third",
    equationDescription: "Profile shape varies by season. The Design Rainfall module (FEH DDF) provides depth-duration-frequency estimates for any UK location.",
    parameters: [
      { name: "Total Depth", symbol: "P", description: "FEH DDF design depth", defaultValue: "Location-dependent", range: "5–300 mm" },
      { name: "Season", symbol: "S", description: "Summer (75%) or Winter (50%)", defaultValue: "Summer", range: "Summer/Winter" },
    ],
    peakPosition: "50% of duration (center)",
    peakIntensityRatio: "~3–5× average intensity",
    applicableRegions: ["England", "Wales", "Scotland", "Northern Ireland"],
    typicalDurations: ["1 hr", "3 hr", "6 hr", "12 hr", "24 hr"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "30-yr", "100-yr", "1000-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "Environment Agency (England)", status: "required", notes: "Required for all flood risk assessments" },
      { jurisdiction: "SEPA (Scotland)", status: "required" },
      { jurisdiction: "NRW (Wales)", status: "required" },
    ],
    standardReference: "Flood Estimation Handbook (FEH), CEH, 1999 (updated 2013)",
    characteristicShape: "Center-peaked (seasonal)",
    similarPatterns: ["FSR (UK)", "Euler Type II"],
    differenceNotes: "FEH replaced FSR and uses updated DDF models. Summer profile is more peaked than winter. FSR used fixed percentile profiles.",
    lastVerified: "2025-01",
    dataSource: "CEH FEH Web Service",
  },
  {
    id: "arr-2019",
    name: "Australian ARR 2019",
    region: "Asian",
    shortDescription: "Australian Rainfall & Runoff standard using ensemble temporal patterns from Bureau data.",
    fullDescription: "ARR 2019 replaced the traditional single design storm approach with ensemble temporal patterns derived from pluviograph data across Australia. The method produces multiple hyetographs for Monte Carlo simulation rather than a single deterministic pattern.",
    history: "Australian Rainfall and Runoff (ARR) was first published in 1958 and revised in 1987. The 2019 edition introduced a paradigm shift to ensemble methods, reflecting modern understanding of rainfall variability.",
    equation: "Ensemble of 10 temporal patterns per duration\nDerived from regionalized pluviograph analysis",
    equationDescription: "ARR 2019 provides sets of temporal patterns rather than a single curve. Each pattern represents a plausible storm shape for the region and duration.",
    parameters: [
      { name: "Total Depth", symbol: "P", description: "Design depth from ARR Data Hub", defaultValue: "Location-dependent", range: "5–500 mm" },
      { name: "Region", symbol: "R", description: "ARR temporal pattern region", defaultValue: "Location-dependent", range: "1–8" },
    ],
    peakPosition: "Variable (ensemble)",
    peakIntensityRatio: "Variable (ensemble)",
    applicableRegions: ["All of Australia", "New Zealand (adapted)"],
    typicalDurations: ["0.5 hr", "1 hr", "3 hr", "6 hr", "12 hr", "24 hr", "72 hr"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "20-yr", "50-yr", "100-yr", "500-yr", "2000-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "All Australian states/territories", status: "required", notes: "Mandated since 2019 for all new studies" },
    ],
    standardReference: "Australian Rainfall and Runoff: A Guide to Flood Estimation (2019), Ball et al.",
    standardUrl: "https://arr.ga.gov.au",
    characteristicShape: "Ensemble (variable)",
    similarPatterns: ["Alternating Block", "Huff distributions"],
    differenceNotes: "ARR 2019 uses ensembles of 10 patterns per scenario rather than a single deterministic pattern. This captures rainfall variability that single patterns miss.",
    lastVerified: "2025-01",
    dataSource: "ARR Data Hub (data.arr-software.org)",
  },
  {
    id: "desbordes",
    name: "Desbordes (IT77)",
    region: "European",
    shortDescription: "French double-triangle hyetograph from Instruction Technique IT77. Standard for urban drainage in France.",
    fullDescription: "The Desbordes rainfall distribution is a double-triangle (bi-triangular) synthetic hyetograph developed for French urban drainage design. It was codified in the Instruction Technique Relative aux Réseaux d'Assainissement des Agglomérations (IT77) issued by the French Ministry of the Interior in 1977. The method derives a storm shape from local IDF parameters using the Montana equation, producing an asymmetric double-triangle pattern with a sharp peak. It remains one of the most widely used design storm methods in France and francophone countries, and is natively supported in InfoWorks ICM (formerly InfoWorks CS) as the 'Desbordes' rainfall profile.",
    history: "Developed by Michel Desbordes at the Université de Montpellier in the 1970s as part of research into synthetic rainfall for sewer network design. Adopted nationally through Instruction Technique IT77 (Circulaire interministérielle n° 77-284 du 22 juin 1977). The method was designed to work with the Montana IDF formula widely used in France (i = a·t^(-b)) and became the de facto standard for French assainissement design. InfoWorks Hydrology (now InfoWorks ICM) incorporated the Desbordes profile for French projects, making it available alongside Euler and Chicago patterns.",
    equation: "Montana IDF: i = a · t^(-b)\n\nDouble-triangle construction:\n- Rising limb from 0 to t_p (peak time)\n- Falling limb from t_p to D (total duration)\n- Peak position: t_p = r · D (typically r ≈ 0.25–0.40)\n- Peak intensity derived from Montana parameters",
    equationDescription: "The hyetograph is constructed by disaggregating the Montana IDF curve into a double-triangle shape. The peak is placed at fraction r of the total duration, with the rising and falling limbs forming two triangles whose total volume equals the design rainfall depth.",
    parameters: [
      { name: "Montana Coefficient", symbol: "a", description: "IDF curve coefficient from local Montana fit", defaultValue: "Location-dependent", range: "3–15 (mm/min units)" },
      { name: "Montana Exponent", symbol: "b", description: "IDF curve exponent", defaultValue: "~0.5–0.8", range: "0.4–0.9" },
      { name: "Peak Position", symbol: "r", description: "Fraction of duration at which peak occurs", defaultValue: "0.375", range: "0.25–0.50" },
      { name: "Total Duration", symbol: "D", description: "Design storm duration", defaultValue: "1 hr", range: "0.25–6 hr" },
    ],
    peakPosition: "25–40% of duration (default r=0.375)",
    peakIntensityRatio: "~4–7× average intensity",
    applicableRegions: ["Metropolitan France", "French overseas territories", "Francophone West Africa", "Francophone North Africa", "Belgium (Wallonia)", "Luxembourg"],
    typicalDurations: ["0.25 hr", "0.5 hr", "1 hr", "2 hr", "3 hr", "6 hr"],
    typicalReturnPeriods: ["2-yr", "5-yr", "10-yr", "20-yr", "50-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "France (national)", status: "required", notes: "Standard per Instruction Technique IT77 for assainissement design" },
      { jurisdiction: "Métropole de Lyon", status: "required", notes: "Required for urban drainage studies" },
      { jurisdiction: "Île-de-France (DRIEE)", status: "accepted", notes: "Accepted alongside ANC standards" },
      { jurisdiction: "Belgium (Wallonia)", status: "accepted", notes: "Used in francophone Belgian practice" },
      { jurisdiction: "InfoWorks ICM / CS", status: "accepted", notes: "Natively supported as built-in rainfall profile" },
    ],
    standardReference: "Instruction Technique Relative aux Réseaux d'Assainissement des Agglomérations, Circulaire interministérielle n° 77-284, 22 juin 1977; Desbordes, M. (1978), Université de Montpellier",
    characteristicShape: "Front-peaked double-triangle",
    similarPatterns: ["Chicago Storm", "Euler Type II", "Desbordes Double-Peak"],
    differenceNotes: "Desbordes uses a double-triangle geometric construction from Montana IDF parameters, while Chicago Storm uses a continuous analytical function. Euler Type II uses block rearrangement. The Desbordes Double-Peak variant adds a secondary peak for long-duration storms. InfoWorks ICM implements Desbordes natively, making it the preferred choice for French sewer modeling projects.",
    lastVerified: "2025-01",
    dataSource: "IT77 / Montana IDF tables (Météo-France)",
  },
  {
    id: "desbordes-double",
    name: "Desbordes Double-Peak",
    region: "European",
    shortDescription: "Dual-peak variant of the Desbordes method for long-duration French urban drainage storms.",
    fullDescription: "The Desbordes Double-Peak distribution extends the classic IT77 single-peak hyetograph by introducing a secondary rainfall peak later in the storm. This variant better represents long-duration convective events common in Mediterranean and southern France, where storms frequently exhibit a lull followed by a second intense burst. It is used when single-triangle patterns underestimate peak flows in combined sewer systems subject to prolonged loading.",
    history: "Developed as a refinement of the original Desbordes method to address observations that long-duration storms in southern France often exhibit bimodal intensity patterns. Research at ENGEES (École Nationale du Génie de l'Eau et de l'Environnement de Strasbourg) and Montpellier validated the dual-peak approach against recorded pluviograph data. The variant gained adoption in French consulting practice for storms exceeding 2 hours and is supported in InfoWorks ICM as a configurable Desbordes profile.",
    equation: "Montana IDF: i = a · t^(-b)\n\nDual-triangle construction:\n- Primary peak at t₁ = r₁ · D\n- Secondary peak at t₂ = r₂ · D\n- Volume split: α · P at first peak, (1-α) · P at second peak\n- Each peak formed as a triangle from Montana-derived intensities",
    equationDescription: "Two separate triangle hyetographs are superimposed. The first peak carries fraction α of the total depth (typically 60–70%), placed early in the storm. The second peak carries the remainder, placed in the latter portion. Both are derived from Montana IDF parameters.",
    parameters: [
      { name: "Montana Coefficient", symbol: "a", description: "IDF curve coefficient from local Montana fit", defaultValue: "Location-dependent", range: "3–15 (mm/min units)" },
      { name: "Montana Exponent", symbol: "b", description: "IDF curve exponent", defaultValue: "~0.5–0.8", range: "0.4–0.9" },
      { name: "Primary Peak Position", symbol: "r₁", description: "Fraction of duration for first peak", defaultValue: "0.30", range: "0.20–0.40" },
      { name: "Secondary Peak Position", symbol: "r₂", description: "Fraction of duration for second peak", defaultValue: "0.75", range: "0.60–0.85" },
      { name: "Volume Split", symbol: "α", description: "Fraction of total depth in first peak", defaultValue: "0.65", range: "0.50–0.80" },
      { name: "Total Duration", symbol: "D", description: "Design storm duration", defaultValue: "3 hr", range: "2–12 hr" },
    ],
    peakPosition: "30% and 75% of duration (dual peaks)",
    peakIntensityRatio: "~3–5× average intensity per peak",
    applicableRegions: ["Metropolitan France (especially Mediterranean)", "Southern France", "Corsica", "French overseas territories", "Francophone West Africa"],
    typicalDurations: ["2 hr", "3 hr", "6 hr", "12 hr"],
    typicalReturnPeriods: ["5-yr", "10-yr", "20-yr", "50-yr", "100-yr"],
    regulatoryAcceptance: [
      { jurisdiction: "France (national)", status: "accepted", notes: "Accepted variant of IT77 for long-duration analysis" },
      { jurisdiction: "DREAL Occitanie", status: "accepted", notes: "Recommended for Mediterranean storm modeling" },
      { jurisdiction: "InfoWorks ICM / CS", status: "accepted", notes: "Supported as configurable dual-peak Desbordes profile" },
    ],
    standardReference: "Desbordes, M. (1978), Université de Montpellier; ENGEES research publications on bimodal storm patterns",
    characteristicShape: "Dual-peaked (bimodal)",
    similarPatterns: ["Desbordes (IT77)", "Chicago Storm", "Huff 4th Quartile"],
    differenceNotes: "The single-peak Desbordes concentrates all energy in one triangle; the double-peak variant splits energy across two peaks, better representing prolonged convective events. Huff 4th Quartile also exhibits late-storm intensity but is empirically derived from Illinois data rather than IDF-based.",
    lastVerified: "2025-01",
    dataSource: "IT77 / Montana IDF tables (Météo-France) / ENGEES research",
  },
];
