import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";
import { generateRainfallData } from "@/lib/rainfallPatterns";
import { patterns as allPatterns } from "@/components/PatternSelector";
import { type UnitSystem, convertIntensity, getIntensityUnit, getDepthUnit, convertDepth } from "@/lib/unitConversions";

interface AllPatternsReportPdfProps {
  depth: number;
  duration: number;
  timeStep: number;
  unitSystem: UnitSystem;
}

interface RowResult {
  idx: number;
  name: string;
  icon: string;
  category: string;
  peakIntensity: number;
  timeToPeak: number;
  totalVolume: number;
  volumeError: number;
  pass: boolean;
}

const categoryLabels: Record<string, string> = {
  swmm: "SWMM / Core",
  us_agency: "US Agency",
  icm: "UK / ICM",
  european: "European",
  scandinavian: "Nordic",
  international: "International",
  asian: "Asian",
  middle_east: "Middle East",
  african: "African",
  latam: "Latin America",
  americas: "Americas",
  oceania: "Oceania",
};

export function AllPatternsReportPdf({ depth, duration, timeStep, unitSystem }: AllPatternsReportPdfProps) {
  const [generating, setGenerating] = useState(false);

  const generate = async () => {
    setGenerating(true);
    try {
      const stepHr = timeStep / 60;
      const intensityUnit = getIntensityUnit(unitSystem);
      const depthUnit = getDepthUnit(unitSystem);
      const exportDepth = convertDepth(depth, "USA", unitSystem);

      // Compute results for all patterns
      const testPatterns = allPatterns.filter(p => p.id !== "custom");
      const rows: RowResult[] = testPatterns.map((p, idx) => {
        const intensities = generateRainfallData(p.id, depth, duration, timeStep);
        const peak = Math.max(...intensities);
        const peakIndex = intensities.indexOf(peak);
        const timeToPeak = (peakIndex * timeStep) / 60;
        const volume = intensities.reduce((s, v) => s + v * stepHr, 0);
        const volumeError = Math.abs(volume - depth) / depth;
        return {
          idx: idx + 1,
          name: p.name,
          icon: p.icon,
          category: p.category,
          peakIntensity: convertIntensity(peak, "USA", unitSystem),
          timeToPeak,
          totalVolume: convertDepth(volume, "USA", unitSystem),
          volumeError,
          pass: volumeError < 0.02,
        };
      });

      const passCount = rows.filter(r => r.pass).length;
      const failCount = rows.length - passCount;
      const maxPeak = rows.reduce((m, r) => (r.peakIntensity > m.peakIntensity ? r : m), rows[0]);
      const minPeak = rows.reduce((m, r) => (r.peakIntensity < m.peakIntensity ? r : m), rows[0]);
      const timestamp = new Date().toLocaleString();
      const reportId = `RCS-QA-${Date.now().toString(36).toUpperCase()}`;

      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
      const pageW = pdf.internal.pageSize.getWidth();
      const margin = 14;
      const contentW = pageW - margin * 2;
      let y = 0;

      // ── Header ──
      pdf.setFillColor(30, 64, 175);
      pdf.rect(0, 0, pageW, 28, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(18);
      pdf.setFont("helvetica", "bold");
      pdf.text("ALL PATTERNS — VOLUME CONSERVATION REPORT", margin, 12);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.text(`Generated by Rain Canvas Studio  •  ${timestamp}  •  Report ID: ${reportId}`, margin, 20);
      pdf.text(`${rows.length} patterns  •  Tolerance: 2%`, margin, 25);
      y = 34;

      // ── Summary cards ──
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(30, 64, 175);
      pdf.text("Test Summary", margin, y);
      y += 6;

      const summaryRows = [
        ["Storm Depth", `${exportDepth.toFixed(unitSystem === "USA" ? 2 : 1)} ${depthUnit}`],
        ["Duration", `${duration} hr`],
        ["Time Step", `${timeStep} min`],
        ["Unit System", unitSystem === "USA" ? "US Customary" : "SI Metric"],
        ["Patterns Tested", `${rows.length}`],
        ["Passed (< 2% error)", `${passCount}`],
        ["Failed (≥ 2% error)", `${failCount}`],
        ["Overall Result", failCount === 0 ? "✓ ALL PASS" : `✗ ${failCount} FAILURES`],
        ["Highest Peak", `${maxPeak.icon} ${maxPeak.name} — ${maxPeak.peakIntensity.toFixed(2)} ${intensityUnit}`],
        ["Lowest Peak", `${minPeak.icon} ${minPeak.name} — ${minPeak.peakIntensity.toFixed(2)} ${intensityUnit}`],
      ];

      pdf.setFontSize(8);
      const halfW = contentW / 2;
      summaryRows.forEach((row, i) => {
        const bg = i % 2 === 0 ? 240 : 250;
        pdf.setFillColor(bg, bg, bg);
        pdf.rect(margin, y, contentW, 5.5, "F");
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(80, 80, 80);
        pdf.text(row[0], margin + 2, y + 3.8);
        pdf.setFont("helvetica", "normal");
        if (row[0] === "Overall Result") {
          pdf.setTextColor(failCount === 0 ? 22 : 220, failCount === 0 ? 163 : 38, failCount === 0 ? 74 : 38);
          pdf.setFont("helvetica", "bold");
        } else {
          pdf.setTextColor(30, 30, 30);
        }
        pdf.text(row[1], margin + halfW, y + 3.8);
        y += 5.5;
      });
      y += 8;

      // ── Results table ──
      const colWidths = [
        contentW * 0.06,  // #
        contentW * 0.28,  // Pattern
        contentW * 0.13,  // Region
        contentW * 0.14,  // Peak
        contentW * 0.11,  // Time-to-Peak
        contentW * 0.14,  // Volume
        contentW * 0.08,  // Error %
        contentW * 0.06,  // Status
      ];
      const headers = ["#", "Pattern", "Region", `Peak (${intensityUnit})`, "Tp (hr)", `Vol (${depthUnit})`, "Err %", "Status"];

      const drawHeader = () => {
        pdf.setFillColor(30, 64, 175);
        pdf.rect(margin, y, contentW, 5.5, "F");
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "bold");
        let x = margin;
        headers.forEach((h, i) => {
          pdf.text(h, x + 1.5, y + 3.8);
          x += colWidths[i];
        });
        y += 5.5;
      };

      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.text("Pattern Results", margin, y);
      y += 6;
      drawHeader();

      const rowH = 4.5;
      rows.forEach((row) => {
        if (y > 255) {
          pdf.addPage();
          y = margin;
          drawHeader();
        }

        const bg = !row.pass
          ? [254, 226, 226]
          : row.idx % 2 === 0
            ? [248, 248, 248]
            : [255, 255, 255];
        pdf.setFillColor(bg[0], bg[1], bg[2]);
        pdf.rect(margin, y, contentW, rowH, "F");

        pdf.setFontSize(6.5);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(50, 50, 50);

        let x = margin;
        const cells = [
          `${row.idx}`,
          `${row.icon} ${row.name}`,
          categoryLabels[row.category] || row.category,
          row.peakIntensity.toFixed(2),
          row.timeToPeak.toFixed(2),
          row.totalVolume.toFixed(unitSystem === "USA" ? 4 : 2),
          `${(row.volumeError * 100).toFixed(3)}%`,
          row.pass ? "✓ PASS" : "✗ FAIL",
        ];

        cells.forEach((c, i) => {
          if (i === cells.length - 1) {
            pdf.setFont("helvetica", "bold");
            pdf.setTextColor(row.pass ? 22 : 220, row.pass ? 163 : 38, row.pass ? 74 : 38);
          }
          pdf.text(c, x + 1.5, y + 3.2);
          if (i === cells.length - 1) {
            pdf.setFont("helvetica", "normal");
            pdf.setTextColor(50, 50, 50);
          }
          x += colWidths[i];
        });
        y += rowH;
      });

      // ── Footer on all pages ──
      const pageCount = pdf.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        pdf.setPage(p);
        const footY = pdf.internal.pageSize.getHeight() - 8;
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, footY - 3, pageW - margin, footY - 3);
        pdf.setFontSize(7);
        pdf.setTextColor(160, 160, 160);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Rain Canvas Studio — Volume Conservation Report — ${reportId}`, margin, footY);
        pdf.text(`Page ${p} of ${pageCount}`, pageW - margin, footY, { align: "right" });
      }

      pdf.save(`AllPatterns_VolumeReport_${depth}${depthUnit}_${duration}hr.pdf`);
      toast.success(`PDF report generated — ${passCount}/${rows.length} passed`);
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("Failed to generate PDF report");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Button onClick={generate} disabled={generating} variant="outline" className="gap-2">
      {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
      {generating ? "Generating…" : "Export PDF Report"}
    </Button>
  );
}
