import { Button } from "@/components/ui/button";
import { Download, FileJson, FileText, Droplets } from "lucide-react";
import { toast } from "sonner";

interface RainfallDataPoint {
  time: number;
  intensity: number;
}

interface ExportButtonsProps {
  data: RainfallDataPoint[];
  pattern: string;
  totalDepth: number;
  duration: number;
  timeStep: number;
}

export function ExportButtons({ data, pattern, totalDepth, duration, timeStep }: ExportButtonsProps) {
  const downloadFile = (content: string, fileName: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportAsCsv = () => {
    let csvContent = "Time (hr),Intensity (in/hr)\n";
    data.forEach(point => {
      csvContent += `${point.time.toFixed(2)},${point.intensity.toFixed(4)}\n`;
    });
    downloadFile(csvContent, 'rainfall_pattern.csv', 'text/csv');
    toast.success("Exported as CSV");
  };

  const exportAsJson = () => {
    const jsonData = {
      pattern,
      totalDepth,
      duration,
      timeStep,
      timeseries: data,
    };
    downloadFile(JSON.stringify(jsonData, null, 2), 'rainfall_pattern.json', 'application/json');
    toast.success("Exported as JSON");
  };

  const generateSwmmScript = () => {
    let script = `; SWMM Rainfall Timeseries Generated by Pattern Painter
; Pattern: ${pattern}
; Total Depth: ${totalDepth} inches
; Duration: ${duration} hours
; Time Step: ${timeStep} minutes

[TIMESERIES]
;Name       Date       Time       Value
RainPattern             00:00     0.0000\n`;

    data.forEach(point => {
      const hours = Math.floor(point.time);
      const minutes = Math.round((point.time - hours) * 60);
      const timeStr = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}`;
      script += `RainPattern             ${timeStr}     ${point.intensity.toFixed(4)}\n`;
    });

    downloadFile(script, 'swmm_rainfall_pattern.txt', 'text/plain');
    toast.success("Generated SWMM script");
  };

  const generateInfoWorksScript = () => {
    // InfoWorks ICM rainfall profile format
    let script = `; InfoWorks ICM Rainfall Profile Generated by Pattern Painter
; Pattern: ${pattern}
; Total Depth: ${totalDepth} inches (${(totalDepth * 25.4).toFixed(2)} mm)
; Duration: ${duration} hours
; Time Step: ${timeStep} minutes

[RAINFALL PROFILE]
;Time(mins)  Intensity(mm/hr)
0            0.0000\n`;

    data.forEach(point => {
      const timeMinutes = (point.time * 60).toFixed(1);
      const intensityMmHr = (point.intensity * 25.4).toFixed(4); // Convert inches/hr to mm/hr
      script += `${timeMinutes.padStart(12)}  ${intensityMmHr}\n`;
    });

    // Add summary statistics
    const totalDepthMm = totalDepth * 25.4;
    const peakIntensity = Math.max(...data.map(d => d.intensity)) * 25.4;
    const peakTime = data[data.findIndex(d => d.intensity === Math.max(...data.map(d => d.intensity)))].time;
    
    script += `\n; Summary Statistics
; Total Depth: ${totalDepthMm.toFixed(2)} mm
; Peak Intensity: ${peakIntensity.toFixed(2)} mm/hr
; Time to Peak: ${peakTime.toFixed(2)} hours
; Storm Duration: ${duration} hours`;

    downloadFile(script, 'infoworks_rainfall_profile.txt', 'text/plain');
    toast.success("Generated InfoWorks ICM profile");
  };

  return (
    <div className="flex flex-wrap gap-3 mt-6">
      <Button onClick={exportAsCsv} variant="secondary" className="gap-2">
        <Download className="w-4 h-4" />
        Export CSV
      </Button>
      <Button onClick={exportAsJson} variant="secondary" className="gap-2">
        <FileJson className="w-4 h-4" />
        Export JSON
      </Button>
      <Button onClick={generateSwmmScript} variant="secondary" className="gap-2">
        <FileText className="w-4 h-4" />
        SWMM Script
      </Button>
      <Button onClick={generateInfoWorksScript} className="gap-2">
        <Droplets className="w-4 h-4" />
        InfoWorks ICM
      </Button>
    </div>
  );
}
