import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FileText, Loader2, Settings } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { type UnitSystem, convertIntensity, convertDepth, getDepthUnit, getIntensityUnit } from "@/lib/unitConversions";

interface RainfallDataPoint {
  time: number;
  intensity: number;
}

interface PdfReportGeneratorProps {
  data: RainfallDataPoint[];
  pattern: string;
  totalDepth: number;
  duration: number;
  timeStep: number;
  unitSystem: UnitSystem;
}

export function PdfReportGenerator({
  data, pattern, totalDepth, duration, timeStep, unitSystem,
}: PdfReportGeneratorProps) {
  const [generating, setGenerating] = useState(false);
  const [showOptions, setShowOptions] = useState(false);
  const [projectName, setProjectName] = useState("");
  const [engineerName, setEngineerName] = useState("");
  const [companyName, setCompanyName] = useState("");

  const generatePdf = async () => {
    setGenerating(true);
    try {
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
      const pageW = pdf.internal.pageSize.getWidth();
      const margin = 18;
      const contentW = pageW - margin * 2;
      let y = margin;

      const depthUnit = getDepthUnit(unitSystem);
      const intensityUnit = getIntensityUnit(unitSystem);
      const exportDepth = convertDepth(totalDepth, "USA", unitSystem);
      const convertedData = data.map(d => ({
        ...d,
        convertedIntensity: convertIntensity(d.intensity, "USA", unitSystem),
      }));
      const peakIntensity = Math.max(...convertedData.map(d => d.convertedIntensity));
      const peakIdx = convertedData.findIndex(d => d.convertedIntensity === peakIntensity);
      const peakTime = peakIdx >= 0 ? data[peakIdx].time : 0;
      const stepHr = timeStep / 60;
      const timestamp = new Date().toLocaleString();
      const reportId = `RCS-${Date.now().toString(36).toUpperCase()}`;

      // Compute incremental depths & cumulative
      const depths = convertedData.map(d => d.convertedIntensity * stepHr);
      const depthSum = depths.reduce((s, v) => s + v, 0);
      const depthError = Math.abs(depthSum - exportDepth) / exportDepth * 100;

      // ── Header bar ──
      pdf.setFillColor(30, 64, 175);
      pdf.rect(0, 0, pageW, 30, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(20);
      pdf.setFont("helvetica", "bold");
      pdf.text("DESIGN STORM REPORT", margin, 13);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.text("Generated by Rain Canvas Studio", margin, 20);
      pdf.text(timestamp, margin, 26);
      pdf.text(`Report ID: ${reportId}`, pageW - margin, 26, { align: "right" });
      y = 38;

      // ── Project Info (optional) ──
      if (projectName || engineerName || companyName) {
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text("Project Information", margin, y);
        y += 5;
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(30, 30, 30);
        if (projectName) { pdf.text(`Project: ${projectName}`, margin + 3, y); y += 5; }
        if (engineerName) { pdf.text(`Engineer: ${engineerName}`, margin + 3, y); y += 5; }
        if (companyName) { pdf.text(`Company: ${companyName}`, margin + 3, y); y += 5; }
        y += 3;
      }

      // ── Storm Parameters Table ──
      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Storm Parameters", margin, y);
      y += 6;

      const metaRows = [
        ["Pattern", pattern],
        ["Total Depth", `${exportDepth.toFixed(unitSystem === "USA" ? 2 : 1)} ${depthUnit}`],
        ["Duration", `${duration} hours`],
        ["Time Step", `${timeStep} minutes`],
        ["Peak Intensity", `${peakIntensity.toFixed(2)} ${intensityUnit}`],
        ["Time to Peak", `${peakTime.toFixed(2)} hours`],
        ["Unit System", unitSystem === "USA" ? "US Customary (inches)" : "SI Metric (mm)"],
        ["Data Points", `${data.length}`],
      ];

      pdf.setFontSize(9);
      const colW = contentW / 2;
      const rowH = 6.5;
      metaRows.forEach((row, i) => {
        const bgColor = i % 2 === 0 ? 240 : 250;
        pdf.setFillColor(bgColor, bgColor, bgColor);
        pdf.rect(margin, y, contentW, rowH, "F");
        pdf.setTextColor(80, 80, 80);
        pdf.setFont("helvetica", "bold");
        pdf.text(row[0], margin + 3, y + 4.5);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(30, 30, 30);
        pdf.text(row[1], margin + colW, y + 4.5);
        y += rowH;
      });
      y += 6;

      // ── Verification Checks ──
      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Verification Checks", margin, y);
      y += 6;

      const checks = [
        ["Mass Balance", `Sum of increments = ${depthSum.toFixed(4)} ${depthUnit}`, depthError < 0.1 ? "✓ PASS" : "✗ FAIL"],
        ["Depth Match", `Error = ${depthError.toFixed(4)}%`, depthError < 0.1 ? "✓ PASS" : "⚠ WARNING"],
        ["Interval Count", `${data.length} × ${timeStep} min = ${(data.length * timeStep / 60).toFixed(1)} hr`, data.length === Math.ceil(duration * 60 / timeStep) ? "✓ PASS" : "✓ OK"],
        ["Non-Negative", `Min = ${Math.min(...depths).toFixed(4)} ${depthUnit}`, Math.min(...depths) >= 0 ? "✓ PASS" : "✗ FAIL"],
      ];

      const checkColWidths = [contentW * 0.25, contentW * 0.55, contentW * 0.2];
      // Header
      pdf.setFillColor(30, 64, 175);
      pdf.rect(margin, y, contentW, 6, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      let xPos = margin;
      ["Check", "Result", "Status"].forEach((h, i) => {
        pdf.text(h, xPos + 2, y + 4.2);
        xPos += checkColWidths[i];
      });
      y += 6;

      pdf.setFontSize(8);
      checks.forEach((row, i) => {
        const bgColor = i % 2 === 0 ? 248 : 255;
        pdf.setFillColor(bgColor, bgColor, bgColor);
        pdf.rect(margin, y, contentW, 5.5, "F");
        xPos = margin;
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(60, 60, 60);
        pdf.text(row[0], xPos + 2, y + 3.8);
        xPos += checkColWidths[0];
        pdf.setFont("helvetica", "normal");
        pdf.text(row[1], xPos + 2, y + 3.8);
        xPos += checkColWidths[1];
        // Color-code status
        if (row[2].includes("PASS") || row[2].includes("OK")) {
          pdf.setTextColor(22, 163, 74);
        } else if (row[2].includes("FAIL")) {
          pdf.setTextColor(220, 38, 38);
        } else {
          pdf.setTextColor(234, 179, 8);
        }
        pdf.setFont("helvetica", "bold");
        pdf.text(row[2], xPos + 2, y + 3.8);
        y += 5.5;
      });
      y += 8;

      // ── Hyetograph Chart ──
      const chartEl = document.querySelector(".recharts-responsive-container")?.parentElement;
      if (chartEl) {
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(13);
        pdf.setFont("helvetica", "bold");
        pdf.text("Rainfall Hyetograph", margin, y);
        y += 4;

        const canvas = await html2canvas(chartEl as HTMLElement, {
          backgroundColor: "#ffffff", scale: 2, useCORS: true,
        });
        const imgData = canvas.toDataURL("image/png");
        const imgW = contentW;
        const imgH = (canvas.height / canvas.width) * imgW;
        pdf.addImage(imgData, "PNG", margin, y, imgW, imgH);
        y += imgH + 3;

        // Caption
        pdf.setTextColor(120, 120, 120);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "italic");
        pdf.text(
          `Figure 1: ${pattern} hyetograph — ${exportDepth.toFixed(2)} ${depthUnit}, ${duration}-hr, ${timeStep}-min intervals`,
          margin, y
        );
        y += 8;
      }

      // ── Timeseries Data Table ──
      if (y > 200) { pdf.addPage(); y = margin; }

      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Timeseries Data", margin, y);
      y += 6;

      const tColWidths = [contentW * 0.08, contentW * 0.15, contentW * 0.22, contentW * 0.22, contentW * 0.22, contentW * 0.11];
      const tHeaders = ["#", "Time (hr)", `Intensity (${intensityUnit})`, `Incr. Depth (${depthUnit})`, `Cumul. Depth (${depthUnit})`, "Cumul. %"];

      const drawTableHeader = () => {
        pdf.setFillColor(30, 64, 175);
        pdf.rect(margin, y, contentW, 6, "F");
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(7.5);
        pdf.setFont("helvetica", "bold");
        let x = margin;
        tHeaders.forEach((h, i) => {
          pdf.text(h, x + 1.5, y + 4.2);
          x += tColWidths[i];
        });
        y += 6;
      };

      drawTableHeader();
      pdf.setFontSize(7);

      let cumDepth = 0;
      data.forEach((point, i) => {
        if (y > 260) {
          pdf.addPage();
          y = margin;
          drawTableHeader();
          pdf.setFontSize(7);
        }

        const intensity = convertedData[i].convertedIntensity;
        const incrDepth = depths[i];
        cumDepth += incrDepth;
        const cumPct = exportDepth > 0 ? (cumDepth / exportDepth * 100) : 0;
        const isPeak = i === peakIdx;

        const bgColor = isPeak ? [254, 243, 199] : (i % 2 === 0 ? [248, 248, 248] : [255, 255, 255]);
        pdf.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
        pdf.rect(margin, y, contentW, 5, "F");

        pdf.setTextColor(60, 60, 60);
        pdf.setFont("helvetica", isPeak ? "bold" : "normal");
        let x = margin;
        const decimals = unitSystem === "USA" ? 4 : 2;
        const cells = [
          `${i + 1}`,
          point.time.toFixed(2),
          intensity.toFixed(decimals),
          incrDepth.toFixed(decimals),
          cumDepth.toFixed(decimals),
          `${cumPct.toFixed(1)}%`,
        ];
        cells.forEach((c, j) => {
          pdf.text(c, x + 1.5, y + 3.6);
          x += tColWidths[j];
        });
        y += 5;
      });

      // ── Footer on all pages ──
      const pageCount = pdf.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        pdf.setPage(p);
        const footY = pdf.internal.pageSize.getHeight() - 8;
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, footY - 3, pageW - margin, footY - 3);
        pdf.setFontSize(7);
        pdf.setTextColor(160, 160, 160);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Rain Canvas Studio — Design Storm Report — ${reportId}`, margin, footY);
        pdf.text(`Page ${p} of ${pageCount}`, pageW - margin, footY, { align: "right" });
      }

      pdf.save(`DesignStorm_${pattern.replace(/\s+/g, '_')}_${exportDepth.toFixed(1)}${depthUnit}_${duration}hr.pdf`);
      toast.success("PDF report generated");
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("Failed to generate PDF");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-2">
      <Collapsible open={showOptions} onOpenChange={setShowOptions}>
        <CollapsibleTrigger asChild>
          <Button variant="ghost" size="sm" className="gap-1.5 text-xs text-muted-foreground h-7 px-2">
            <Settings className="w-3 h-3" />
            {showOptions ? "Hide" : "Add"} project details
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-2 p-3 bg-muted/50 rounded-lg mt-1">
            <div>
              <Label className="text-xs">Project Name</Label>
              <Input value={projectName} onChange={e => setProjectName(e.target.value)} placeholder="Project name..." className="mt-1 h-8 text-xs" />
            </div>
            <div>
              <Label className="text-xs">Engineer</Label>
              <Input value={engineerName} onChange={e => setEngineerName(e.target.value)} placeholder="Engineer name..." className="mt-1 h-8 text-xs" />
            </div>
            <div>
              <Label className="text-xs">Company</Label>
              <Input value={companyName} onChange={e => setCompanyName(e.target.value)} placeholder="Company name..." className="mt-1 h-8 text-xs" />
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>

      <Button onClick={generatePdf} disabled={generating} className="gap-2">
        {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
        {generating ? "Generating…" : "PDF Engineering Report"}
      </Button>
    </div>
  );
}
