import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { type UnitSystem, convertIntensity, convertDepth, getDepthUnit, getIntensityUnit } from "@/lib/unitConversions";

interface RainfallDataPoint {
  time: number;
  intensity: number;
}

interface PdfReportGeneratorProps {
  data: RainfallDataPoint[];
  pattern: string;
  totalDepth: number;
  duration: number;
  timeStep: number;
  unitSystem: UnitSystem;
}

export function PdfReportGenerator({
  data,
  pattern,
  totalDepth,
  duration,
  timeStep,
  unitSystem,
}: PdfReportGeneratorProps) {
  const [generating, setGenerating] = useState(false);

  const generatePdf = async () => {
    setGenerating(true);
    try {
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
      const pageW = pdf.internal.pageSize.getWidth();
      const margin = 18;
      const contentW = pageW - margin * 2;
      let y = margin;

      const depthUnit = getDepthUnit(unitSystem);
      const intensityUnit = getIntensityUnit(unitSystem);
      const exportDepth = convertDepth(totalDepth, "USA", unitSystem);
      const peakIntensity = Math.max(
        ...data.map((d) => convertIntensity(d.intensity, "USA", unitSystem))
      );
      const peakIdx = data.findIndex(
        (d) => d.intensity === Math.max(...data.map((p) => p.intensity))
      );
      const peakTime = peakIdx >= 0 ? data[peakIdx].time : 0;
      const timestamp = new Date().toLocaleString();

      // ── Header bar ──
      pdf.setFillColor(30, 64, 175); // blue-800
      pdf.rect(0, 0, pageW, 28, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(18);
      pdf.setFont("helvetica", "bold");
      pdf.text("Rainfall Design Storm Report", margin, 12);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.text("Generated by Rain Canvas Studio", margin, 19);
      pdf.text(timestamp, pageW - margin, 19, { align: "right" });
      y = 36;

      // ── Storm Metadata Table ──
      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Storm Parameters", margin, y);
      y += 6;

      const metaRows = [
        ["Pattern", pattern],
        ["Total Depth", `${exportDepth.toFixed(unitSystem === "USA" ? 2 : 1)} ${depthUnit}`],
        ["Duration", `${duration} hours`],
        ["Time Step", `${timeStep} minutes`],
        ["Peak Intensity", `${peakIntensity.toFixed(2)} ${intensityUnit}`],
        ["Time to Peak", `${peakTime.toFixed(2)} hours`],
        ["Unit System", unitSystem],
        ["Data Points", `${data.length}`],
      ];

      pdf.setFontSize(9);
      const colW = contentW / 2;
      const rowH = 6.5;

      metaRows.forEach((row, i) => {
        const bgColor = i % 2 === 0 ? 240 : 250;
        pdf.setFillColor(bgColor, bgColor, bgColor);
        pdf.rect(margin, y, contentW, rowH, "F");
        pdf.setTextColor(80, 80, 80);
        pdf.setFont("helvetica", "bold");
        pdf.text(row[0], margin + 3, y + 4.5);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(30, 30, 30);
        pdf.text(row[1], margin + colW, y + 4.5);
        y += rowH;
      });

      y += 8;

      // ── Hyetograph Chart (capture from DOM) ──
      const chartEl = document.querySelector(".recharts-responsive-container")?.parentElement;
      if (chartEl) {
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(13);
        pdf.setFont("helvetica", "bold");
        pdf.text("Rainfall Hyetograph", margin, y);
        y += 4;

        const canvas = await html2canvas(chartEl as HTMLElement, {
          backgroundColor: "#ffffff",
          scale: 2,
          useCORS: true,
        });
        const imgData = canvas.toDataURL("image/png");
        const imgW = contentW;
        const imgH = (canvas.height / canvas.width) * imgW;
        pdf.addImage(imgData, "PNG", margin, y, imgW, imgH);
        y += imgH + 8;
      }

      // ── Timeseries Data Table ──
      // Check if we need a new page
      if (y > 200) {
        pdf.addPage();
        y = margin;
      }

      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Timeseries Data", margin, y);
      y += 6;

      // Table header
      pdf.setFillColor(30, 64, 175);
      pdf.rect(margin, y, contentW, 6, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      const colWidths = [contentW * 0.15, contentW * 0.25, contentW * 0.25, contentW * 0.35];
      const headers = ["#", `Time (hr)`, `Intensity (${intensityUnit})`, `Incr. Depth (${depthUnit})`];
      let xPos = margin;
      headers.forEach((h, i) => {
        pdf.text(h, xPos + 2, y + 4.2);
        xPos += colWidths[i];
      });
      y += 6;

      // Table rows
      pdf.setFontSize(7.5);
      const stepHr = timeStep / 60;
      data.forEach((point, i) => {
        if (y > 260) {
          pdf.addPage();
          y = margin;
          // Repeat header on new page
          pdf.setFillColor(30, 64, 175);
          pdf.rect(margin, y, contentW, 6, "F");
          pdf.setTextColor(255, 255, 255);
          pdf.setFontSize(8);
          pdf.setFont("helvetica", "bold");
          let xH = margin;
          headers.forEach((h, j) => {
            pdf.text(h, xH + 2, y + 4.2);
            xH += colWidths[j];
          });
          y += 6;
          pdf.setFontSize(7.5);
        }

        const bgColor = i % 2 === 0 ? 248 : 255;
        pdf.setFillColor(bgColor, bgColor, bgColor);
        pdf.rect(margin, y, contentW, 5, "F");

        const intensity = convertIntensity(point.intensity, "USA", unitSystem);
        const incrDepth = intensity * stepHr;

        pdf.setTextColor(60, 60, 60);
        pdf.setFont("helvetica", "normal");
        xPos = margin;
        const cells = [
          `${i + 1}`,
          point.time.toFixed(2),
          intensity.toFixed(unitSystem === "USA" ? 4 : 2),
          incrDepth.toFixed(unitSystem === "USA" ? 4 : 2),
        ];
        cells.forEach((c, j) => {
          pdf.text(c, xPos + 2, y + 3.6);
          xPos += colWidths[j];
        });
        y += 5;
      });

      // ── Footer ──
      const pageCount = pdf.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        pdf.setPage(p);
        const footY = pdf.internal.pageSize.getHeight() - 8;
        pdf.setFontSize(7);
        pdf.setTextColor(160, 160, 160);
        pdf.text(
          "Rain Canvas Studio — Synthetic Design Storm Report",
          margin,
          footY
        );
        pdf.text(`Page ${p} of ${pageCount}`, pageW - margin, footY, {
          align: "right",
        });
      }

      pdf.save("design_storm_report.pdf");
      toast.success("PDF report generated");
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("Failed to generate PDF");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Button onClick={generatePdf} disabled={generating} className="gap-2">
      {generating ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <FileText className="w-4 h-4" />
      )}
      {generating ? "Generating…" : "PDF Report"}
    </Button>
  );
}
