import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import type jsPDF from "jspdf";
import { type UnitSystem, convertIntensity, convertDepth, getDepthUnit, getIntensityUnit } from "@/lib/unitConversions";
import { type PatternType } from "@/lib/rainfallPatterns";
import { getPatternEquation } from "@/lib/patternEquations";

interface RainfallDataPoint {
  time: number;
  intensity: number;
}

interface PdfReportGeneratorProps {
  data: RainfallDataPoint[];
  pattern: string;
  patternKey?: PatternType;
  totalDepth: number;
  duration: number;
  timeStep: number;
  unitSystem: UnitSystem;
  projectName?: string;
  engineerName?: string;
  companyName?: string;
}

export function PdfReportGenerator({
  data, pattern, patternKey, totalDepth, duration, timeStep, unitSystem,
  projectName = "", engineerName = "", companyName = "",
}: PdfReportGeneratorProps) {
  const [generating, setGenerating] = useState(false);

  const generatePdf = async () => {
    setGenerating(true);
    try {
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const margin = 18;
      const contentW = pageW - margin * 2;
      let y = margin;

      const depthUnit = getDepthUnit(unitSystem);
      const intensityUnit = getIntensityUnit(unitSystem);
      const exportDepth = convertDepth(totalDepth, "USA", unitSystem);
      const convertedData = data.map(d => ({
        ...d,
        convertedIntensity: convertIntensity(d.intensity, "USA", unitSystem),
      }));
      const peakIntensity = Math.max(...convertedData.map(d => d.convertedIntensity));
      const peakIdx = convertedData.findIndex(d => d.convertedIntensity === peakIntensity);
      const peakTime = peakIdx >= 0 ? data[peakIdx].time : 0;
      const stepHr = timeStep / 60;
      const timestamp = new Date().toLocaleString();
      const reportId = `RCS-${Date.now().toString(36).toUpperCase()}`;

      // Compute incremental depths & cumulative
      const depths = convertedData.map(d => d.convertedIntensity * stepHr);
      const depthSum = depths.reduce((s, v) => s + v, 0);
      const depthError = Math.abs(depthSum - exportDepth) / exportDepth * 100;

      // Helper: check page break
      const checkPage = (needed: number) => {
        if (y + needed > pageH - 15) {
          pdf.addPage();
          y = margin;
        }
      };

      // ── Header bar ──
      pdf.setFillColor(30, 64, 175);
      pdf.rect(0, 0, pageW, 30, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(20);
      pdf.setFont("helvetica", "bold");
      pdf.text("DESIGN STORM REPORT", margin, 13);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.text("Generated by Rain Canvas Studio", margin, 20);
      pdf.text(timestamp, margin, 26);
      pdf.text(`Report ID: ${reportId}`, pageW - margin, 26, { align: "right" });
      y = 38;

      // ── Project Info (optional) ──
      if (projectName || engineerName || companyName) {
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text("Project Information", margin, y);
        y += 5;
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(30, 30, 30);
        if (projectName) { pdf.text(`Project: ${projectName}`, margin + 3, y); y += 5; }
        if (engineerName) { pdf.text(`Engineer: ${engineerName}`, margin + 3, y); y += 5; }
        if (companyName) { pdf.text(`Company: ${companyName}`, margin + 3, y); y += 5; }
        y += 3;
      }

      // ── Storm Parameters Table ──
      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Storm Parameters", margin, y);
      y += 6;

      const metaRows = [
        ["Pattern", pattern],
        ["Total Depth", `${exportDepth.toFixed(unitSystem === "USA" ? 2 : 1)} ${depthUnit}`],
        ["Duration", `${duration} hours`],
        ["Time Step", `${timeStep} minutes`],
        ["Peak Intensity", `${peakIntensity.toFixed(2)} ${intensityUnit}`],
        ["Time to Peak", `${peakTime.toFixed(2)} hours`],
        ["Unit System", unitSystem === "USA" ? "US Customary (inches)" : "SI Metric (mm)"],
        ["Data Points", `${data.length}`],
      ];

      pdf.setFontSize(9);
      const colW = contentW / 2;
      const rowH = 6.5;
      metaRows.forEach((row, i) => {
        const bgColor = i % 2 === 0 ? 240 : 250;
        pdf.setFillColor(bgColor, bgColor, bgColor);
        pdf.rect(margin, y, contentW, rowH, "F");
        pdf.setTextColor(80, 80, 80);
        pdf.setFont("helvetica", "bold");
        pdf.text(row[0], margin + 3, y + 4.5);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(30, 30, 30);
        pdf.text(row[1], margin + colW, y + 4.5);
        y += rowH;
      });
      y += 6;

      // ── Pattern Equations & Source ──
      const equationInfo = patternKey ? getPatternEquation(patternKey) : undefined;
      if (equationInfo) {
        checkPage(60);

        // Section: Pattern Source & Reference
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(13);
        pdf.setFont("helvetica", "bold");
        pdf.text("Pattern Source & Reference", margin, y);
        y += 6;

        const refRows = [
          ["Pattern Name", equationInfo.name],
          ["Category", equationInfo.category === 'cumulative' ? 'Cumulative Distribution' : equationInfo.category === 'intensity' ? 'Intensity Function' : 'Empirical Method'],
          ["Reference", equationInfo.reference.title],
          ["Citation", equationInfo.reference.citation],
          ["Year", String(equationInfo.reference.year)],
        ];
        if (equationInfo.reference.link) {
          refRows.push(["URL", equationInfo.reference.link]);
        }

        pdf.setFontSize(9);
        refRows.forEach((row, i) => {
          const bgColor = i % 2 === 0 ? 240 : 250;
          pdf.setFillColor(bgColor, bgColor, bgColor);
          pdf.rect(margin, y, contentW, rowH, "F");
          pdf.setTextColor(80, 80, 80);
          pdf.setFont("helvetica", "bold");
          pdf.text(row[0], margin + 3, y + 4.5);
          pdf.setFont("helvetica", "normal");
          pdf.setTextColor(30, 30, 30);
          // Truncate long URLs
          const val = row[1].length > 80 ? row[1].slice(0, 77) + "..." : row[1];
          pdf.text(val, margin + colW * 0.4, y + 4.5);
          y += rowH;
        });
        y += 4;

        // Notes
        if (equationInfo.notes) {
          checkPage(15);
          pdf.setFillColor(240, 248, 255);
          pdf.rect(margin, y, contentW, 10, "F");
          pdf.setFontSize(8);
          pdf.setTextColor(60, 60, 60);
          pdf.setFont("helvetica", "italic");
          const noteLines = pdf.splitTextToSize(`Note: ${equationInfo.notes}`, contentW - 6);
          pdf.text(noteLines, margin + 3, y + 4);
          y += Math.max(10, noteLines.length * 4 + 4);
          y += 3;
        }

        // Section: Equations Used
        checkPage(30);
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(13);
        pdf.setFont("helvetica", "bold");
        pdf.text("Equations Used", margin, y);
        y += 6;

        equationInfo.equations.forEach((eq) => {
          checkPage(20);

          // Equation label
          pdf.setFillColor(30, 64, 175);
          pdf.setTextColor(255, 255, 255);
          pdf.setFontSize(8);
          pdf.setFont("helvetica", "bold");
          const labelW = pdf.getTextWidth(eq.label) + 6;
          pdf.roundedRect(margin, y, labelW, 5, 1, 1, "F");
          pdf.text(eq.label, margin + 3, y + 3.6);
          y += 7;

          // Equation text (plain text rendering of LaTeX — strip LaTeX commands for readability)
          const plainEq = eq.latex
            .replace(/\\begin\{cases\}/g, '{ ')
            .replace(/\\end\{cases\}/g, ' }')
            .replace(/\\\\/g, ' | ')
            .replace(/\\left[.(]/g, '(')
            .replace(/\\right[.)]/g, ')')
            .replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '($1)/($2)')
            .replace(/\\cdot/g, '·')
            .replace(/\\leq/g, '≤')
            .replace(/\\geq/g, '≥')
            .replace(/\\approx/g, '≈')
            .replace(/\\times/g, '×')
            .replace(/\\sum_\{[^}]*\}\^\{[^}]*\}/g, 'Σ')
            .replace(/\\Delta/g, 'Δ')
            .replace(/\\bar\{([^}]+)\}/g, '$1̄')
            .replace(/\\quad/g, '  ')
            .replace(/\{/g, '')
            .replace(/\}/g, '')
            .replace(/\^/g, '^')
            .replace(/_/g, '_')
            .replace(/\s+/g, ' ')
            .trim();

          pdf.setFillColor(248, 248, 248);
          const eqLines = pdf.splitTextToSize(plainEq, contentW - 10);
          const eqH = Math.max(8, eqLines.length * 4 + 4);
          pdf.rect(margin, y, contentW, eqH, "F");
          pdf.setFontSize(8);
          pdf.setFont("courier", "normal");
          pdf.setTextColor(30, 30, 30);
          pdf.text(eqLines, margin + 5, y + 4);
          y += eqH + 2;

          // Description
          pdf.setFontSize(8);
          pdf.setFont("helvetica", "normal");
          pdf.setTextColor(100, 100, 100);
          pdf.text(eq.description, margin + 3, y + 1);
          y += 5;
        });
        y += 3;

        // Variables table
        if (equationInfo.variables.length > 0) {
          checkPage(20);
          pdf.setTextColor(30, 64, 175);
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "bold");
          pdf.text("Variables", margin, y);
          y += 5;

          // Header
          pdf.setFillColor(30, 64, 175);
          pdf.rect(margin, y, contentW, 5.5, "F");
          pdf.setTextColor(255, 255, 255);
          pdf.setFontSize(7.5);
          pdf.text("Symbol", margin + 3, y + 3.8);
          pdf.text("Meaning", margin + contentW * 0.2, y + 3.8);
          y += 5.5;

          equationInfo.variables.forEach((v, i) => {
            checkPage(6);
            const bgColor = i % 2 === 0 ? 248 : 255;
            pdf.setFillColor(bgColor, bgColor, bgColor);
            pdf.rect(margin, y, contentW, 5, "F");
            pdf.setFontSize(7.5);
            pdf.setFont("courier", "normal");
            pdf.setTextColor(30, 30, 30);
            const sym = v.symbol.replace(/\\/g, '').replace(/\{/g, '').replace(/\}/g, '');
            pdf.text(sym, margin + 3, y + 3.5);
            pdf.setFont("helvetica", "normal");
            pdf.setTextColor(60, 60, 60);
            const meaningLines = pdf.splitTextToSize(v.meaning, contentW * 0.75);
            pdf.text(meaningLines[0], margin + contentW * 0.2, y + 3.5);
            y += 5;
          });
          y += 4;
        }
      }

      // ── Verification Checks ──
      checkPage(40);
      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Verification Checks", margin, y);
      y += 6;

      const checks = [
        ["Mass Balance", `Sum of increments = ${depthSum.toFixed(4)} ${depthUnit}`, depthError < 0.1 ? "✓ PASS" : "✗ FAIL"],
        ["Depth Match", `Error = ${depthError.toFixed(4)}%`, depthError < 0.1 ? "✓ PASS" : "⚠ WARNING"],
        ["Interval Count", `${data.length} × ${timeStep} min = ${(data.length * timeStep / 60).toFixed(1)} hr`, data.length === Math.ceil(duration * 60 / timeStep) ? "✓ PASS" : "✓ OK"],
        ["Non-Negative", `Min = ${Math.min(...depths).toFixed(4)} ${depthUnit}`, Math.min(...depths) >= 0 ? "✓ PASS" : "✗ FAIL"],
      ];

      const checkColWidths = [contentW * 0.25, contentW * 0.55, contentW * 0.2];
      // Header
      pdf.setFillColor(30, 64, 175);
      pdf.rect(margin, y, contentW, 6, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      let xPos = margin;
      ["Check", "Result", "Status"].forEach((h, i) => {
        pdf.text(h, xPos + 2, y + 4.2);
        xPos += checkColWidths[i];
      });
      y += 6;

      pdf.setFontSize(8);
      checks.forEach((row, i) => {
        const bgColor = i % 2 === 0 ? 248 : 255;
        pdf.setFillColor(bgColor, bgColor, bgColor);
        pdf.rect(margin, y, contentW, 5.5, "F");
        xPos = margin;
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(60, 60, 60);
        pdf.text(row[0], xPos + 2, y + 3.8);
        xPos += checkColWidths[0];
        pdf.setFont("helvetica", "normal");
        pdf.text(row[1], xPos + 2, y + 3.8);
        xPos += checkColWidths[1];
        if (row[2].includes("PASS") || row[2].includes("OK")) {
          pdf.setTextColor(22, 163, 74);
        } else if (row[2].includes("FAIL")) {
          pdf.setTextColor(220, 38, 38);
        } else {
          pdf.setTextColor(234, 179, 8);
        }
        pdf.setFont("helvetica", "bold");
        pdf.text(row[2], xPos + 2, y + 3.8);
        y += 5.5;
      });
      y += 8;

      // ── Hyetograph Chart ──
      const chartEl = document.querySelector(".recharts-responsive-container")?.parentElement;
      if (chartEl) {
        checkPage(80);
        pdf.setTextColor(30, 64, 175);
        pdf.setFontSize(13);
        pdf.setFont("helvetica", "bold");
        pdf.text("Rainfall Hyetograph", margin, y);
        y += 4;

        const canvas = await html2canvas(chartEl as HTMLElement, {
          backgroundColor: "#ffffff", scale: 2, useCORS: true,
        });
        const imgData = canvas.toDataURL("image/png");
        const imgW = contentW;
        const imgH = (canvas.height / canvas.width) * imgW;
        pdf.addImage(imgData, "PNG", margin, y, imgW, imgH);
        y += imgH + 3;

        // Caption
        pdf.setTextColor(120, 120, 120);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "italic");
        pdf.text(
          `Figure 1: ${pattern} hyetograph — ${exportDepth.toFixed(2)} ${depthUnit}, ${duration}-hr, ${timeStep}-min intervals`,
          margin, y
        );
        y += 8;
      }

      // ── Timeseries Data Table ──
      checkPage(30);

      pdf.setTextColor(30, 64, 175);
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.text("Timeseries Data", margin, y);
      y += 6;

      const tColWidths = [contentW * 0.08, contentW * 0.15, contentW * 0.22, contentW * 0.22, contentW * 0.22, contentW * 0.11];
      const tHeaders = ["#", "Time (hr)", `Intensity (${intensityUnit})`, `Incr. Depth (${depthUnit})`, `Cumul. Depth (${depthUnit})`, "Cumul. %"];

      const drawTableHeader = () => {
        pdf.setFillColor(30, 64, 175);
        pdf.rect(margin, y, contentW, 6, "F");
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(7.5);
        pdf.setFont("helvetica", "bold");
        let x = margin;
        tHeaders.forEach((h, i) => {
          pdf.text(h, x + 1.5, y + 4.2);
          x += tColWidths[i];
        });
        y += 6;
      };

      drawTableHeader();
      pdf.setFontSize(7);

      let cumDepth = 0;
      data.forEach((point, i) => {
        if (y > 260) {
          pdf.addPage();
          y = margin;
          drawTableHeader();
          pdf.setFontSize(7);
        }

        const intensity = convertedData[i].convertedIntensity;
        const incrDepth = depths[i];
        cumDepth += incrDepth;
        const cumPct = exportDepth > 0 ? (cumDepth / exportDepth * 100) : 0;
        const isPeak = i === peakIdx;

        const bgColor = isPeak ? [254, 243, 199] : (i % 2 === 0 ? [248, 248, 248] : [255, 255, 255]);
        pdf.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
        pdf.rect(margin, y, contentW, 5, "F");

        pdf.setTextColor(60, 60, 60);
        pdf.setFont("helvetica", isPeak ? "bold" : "normal");
        let x = margin;
        const decimals = unitSystem === "USA" ? 4 : 2;
        const cells = [
          `${i + 1}`,
          point.time.toFixed(2),
          intensity.toFixed(decimals),
          incrDepth.toFixed(decimals),
          cumDepth.toFixed(decimals),
          `${cumPct.toFixed(1)}%`,
        ];
        cells.forEach((c, j) => {
          pdf.text(c, x + 1.5, y + 3.6);
          x += tColWidths[j];
        });
        y += 5;
      });

      // ── Footer on all pages ──
      const pageCount = pdf.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        pdf.setPage(p);
        const footY = pdf.internal.pageSize.getHeight() - 8;
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, footY - 3, pageW - margin, footY - 3);
        pdf.setFontSize(7);
        pdf.setTextColor(160, 160, 160);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Rain Canvas Studio — Design Storm Report — ${reportId}`, margin, footY);
        pdf.text(`Page ${p} of ${pageCount}`, pageW - margin, footY, { align: "right" });
      }

      pdf.save(`DesignStorm_${pattern.replace(/\s+/g, '_')}_${exportDepth.toFixed(1)}${depthUnit}_${duration}hr.pdf`);
      toast.success("PDF report generated");
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("Failed to generate PDF");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Button onClick={generatePdf} disabled={generating} className="gap-2">
      {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
      {generating ? "Generating…" : "PDF Engineering Report"}
    </Button>
  );
}
